// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_productivity_factor = "CgkI86T1-IoaEAIQDA"; // <GPGSID>
        public const string achievement_scholar = "CgkI86T1-IoaEAIQAw"; // <GPGSID>
        public const string achievement_finally_some_good_management = "CgkI86T1-IoaEAIQCA"; // <GPGSID>
        public const string achievement_grim_reaper = "CgkI86T1-IoaEAIQBg"; // <GPGSID>
        public const string achievement_builder = "CgkI86T1-IoaEAIQBA"; // <GPGSID>
        public const string achievement_greed_before_need = "CgkI86T1-IoaEAIQBw"; // <GPGSID>
        public const string achievement_student = "CgkI86T1-IoaEAIQAQ"; // <GPGSID>
        public const string achievement_scientific_worker = "CgkI86T1-IoaEAIQAg"; // <GPGSID>
        public const string achievement_mad_scientist = "CgkI86T1-IoaEAIQCg"; // <GPGSID>
        public const string achievement_chemical_engineering = "CgkI86T1-IoaEAIQEA"; // <GPGSID>
        public const string achievement_youve_lasted_so_far_heh = "CgkI86T1-IoaEAIQAA"; // <GPGSID>
        public const string leaderboard_healed_humans = "CgkI86T1-IoaEAIQEQ"; // <GPGSID>
        public const string achievement_man_of_honor = "CgkI86T1-IoaEAIQCQ"; // <GPGSID>
        public const string achievement_a_new_beginning = "CgkI86T1-IoaEAIQCw"; // <GPGSID>
        public const string achievement_life_saver = "CgkI86T1-IoaEAIQBQ"; // <GPGSID>

}

